module.exports = Object.freeze({
  // 🔐 Authentication Events
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ACCESS_TOKEN: "ACCESS_TOKEN",

  // 👤 Account Management
  REGISTER: "REGISTER",
  ACTIVATE: "ACTIVATE",
  DEACTIVATE: "DEACTIVATE",
  BLOCKED: "BLOCKED",
  UNBLOCKED: "UNBLOCKED",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  UPDATE_ACCOUNT_DETAILS: "UPDATE_ACCOUNT_DETAILS",

  // 🧾 Account Info Retrieval
  PROVIDE_USER_ACCOUNT_DETAILS: "PROVIDE_USER_ACCOUNT_DETAILS",
  PROVIDE_MY_ACCOUNT_DETAILS: "PROVIDE_MY_ACCOUNT_DETAILS",
  GET_TOTAL_REGISTERED_USERS: "GET_TOTAL_REGISTERED_USERS",

  // 💻 Device Info
  GET_USER_ACTIVE_DEVICES: "GET_USER_ACTIVE_DEVICES",
  GET_MY_ACTIVE_DEVICES: "GET_MY_ACTIVE_DEVICES",

  // 🛠️ Admin/Internal Use
  SET_ACCESS_TOKEN_FOR_ADMIN: "SET_ACCESS_TOKEN_FOR_ADMIN",
  CHECK_AUTH_LOGS: "CHECK_AUTH_LOGS",

  // 🧹 CRON Job Cleanup Events
  CLEAN_UP_DEACTIVATED_USER: "CLEAN_UP_DEACTIVATED_USER",
  CLEAN_UP_DEVICE_RATE_LIMIT: "CLEAN_UP_DEVICE_RATE_LIMIT",
  CLEAN_UP_AUTH_LOGS: "CLEAN_UP_AUTH_LOGS"
});
