// ========== 🔒 DEVICE BLOCK & UNBLOCK REASONS ENUMS ==========

const DEVICE_BLOCK_REASONS = Object.freeze({
    SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
    TOO_MANY_FAILED_ATTEMPTS: "TOO_MANY_FAILED_ATTEMPTS",
    REPORTED_BY_USER: "REPORTED_BY_USER",
    BLOCKED_BY_ADMIN: "BLOCKED_BY_ADMIN",
    UNKNOWN_DEVICE_LOGIN: "UNKNOWN_DEVICE_LOGIN",
    COMPROMISED_CREDENTIALS: "COMPROMISED_CREDENTIALS"
});

const DEVICE_UNBLOCK_REASONS = Object.freeze({
    FALSE_POSITIVE: "FALSE_POSITIVE",
    MANUAL_REVIEW_CLEARED: "MANUAL_REVIEW_CLEARED",
    REPORTED_AS_SAFE: "REPORTED_AS_SAFE",
    UNBLOCKED_BY_ADMIN: "UNBLOCKED_BY_ADMIN"
});

module.exports = {
    DEVICE_BLOCK_REASONS,
    DEVICE_UNBLOCK_REASONS
};
